version: 1
root:
  level: INFO
  handlers: [consoleHandler]

loggers:
  web_app:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  node_tags:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  host_configuration:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  sbom:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false

formatters:
  simpleFormatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

