clusterName: "Kubernetes Cluster"
podScanner:
  enabled: true
  image:
    repository: "bjornvb/k8s-pod-scanner"
    pullPolicy: "IfNotPresent"
    tag: "0.2.11"
  #Settings determining how the scanner integrates with container manager
  scannerIntegration:
    #Comma-separated list of potential places the docer socket could be on the scanner container.
    potentialDockerSocketLocations: "/host/run/docker.sock"
    #Comma-separated list of potential directories where ContainerD is storing its image snapshots
    potentialContainerDSnapshotLocations: "/host/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots,/host/var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots,/host/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots"
  aws:
    #Prefix for all tags retrieved from AWS VMs
    tagPrefix: "aws_"
    #If running on AWS, retrieve all tags, except the following ones specified as comma-separated list
    #exludeTagList: "billingProducts,devpayProductCodes,instanceType,kernelId,marketplaceProductCodes,pendingTime,ramdiskId,version"
    exludeTagList: ""
    #If running on AWS, only retrieve the following tags specified as comma-separated list
    #Empty means all tags will be returned
    includeTagList: "accountId,architecture,availabilityZone,imageId,instanceId,privateIp,region"
    #includeTagList: ""
  gcp:
    #Prefix for all tags retrieved from AWS VMs
    tagPrefix: "gcp_"
    #If running on GCP, retrieve all tags, except the following ones specified as comma-separated list
    #exludeTagList: "configure-sh,disable-legacy-endpoints,gci-metrics-enabled,gci-update-strategy,google-compute-enable-pcid,instance-template,kube-env,kubeconfig,kubelet-config,serial-port-logging-enable,user-data,kube-labels"
    exludeTagList: ""
    #If running on GCP, only retrieve the following tags specified as comma-separated list
    #Empty means all tags will be returned
    includeTagList: "cluster-location,cluster-name,cluster-uid,created-by"
    #includeTagList: ""
vulnerabilityCoordinator:
  enabled: true
  # Option to turn on and off the container scanner
  scanContainers: true
  # Option to turn on and off the node / host scanner
  scanNodes: true
  externalStorage: true
  # Refresh the cache to ensure data consistency every 30 minutes
  cacheRefreshMinuteInterval: 30
  # How often to check if the vulnerability database changes, which will trigger a rescan of all images and nodes
  checkRemoteScannerMetadataInterval: 30
  # How often to purge the scan cache - every 12 hrs
  purgeScanCacheInterval: 720
  image:
    repository: "bjornvb/k8s-scanner-vulnerability-coordinator"
    pullPolicy: "IfNotPresent"
    tag: "0.2.11"
webFrontend:
  enabled: true
  # How is the web frontend exposed to the world?
  # ClusterIP, NodePort or LoadBalancer
  serviceType: ClusterIP
  image:
    repository: "bjornvb/k8s-scanner-web-frontend"
    pullPolicy: "IfNotPresent"
    tag: "0.2.11"
openTelemetryCollector:
  enabled: false
  #How often does the collector forward metrics
  scrapeInterval: 30s
  logLevel: info
  image:
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: "IfNotPresent"
    tag: "0.117.0"
  exporters:
    otlp:
      enabled: true
      # Example: otelcol2:4317
      endpoint: ""
      tls:
        insecure: false
    otlphttp:
      # Can be used to connect to Prometheus
      enabled: false
      # Example for connecting to Prometheus: http://prometheus-operated:9090/api/v1/otlp
      endpoint: ""
      tls:
        insecure: false
