version: 1
root:
  level: INFO
  handlers: [consoleHandler]

loggers:
  api_cache:
    level: INFO
    handlers: [consoleHandler]
    propagate: false
  file_manager:
    level: INFO
    handlers: [consoleHandler]
    propagate: false
  metrics:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  scheduler:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  app_status_manager:
    level: INFO
    handlers: [consoleHandler]
    propagate: false
  kubernetes_adapter:
    level: INFO
    handlers: [consoleHandler]
    propagate: false
  node_cache: #Not in use
    level: INFO
    handlers: [consoleHandler]
    propagate: false
  vulnerability_coordinator:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  container_cache:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  logging_config: #Not in use
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  pod_scanner:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false
  web_app:
    level: DEBUG
    handlers: [consoleHandler]
    propagate: false

formatters:
  simpleFormatter:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simpleFormatter
    stream: ext://sys.stdout

